export const MainText = [ 'Ok ladies, now let’s get in formation',
    'Oops! Let’s do it again.',
    'Purse first. Let’s go.',
    'You will never rain on our parade.',
    'Who run the world?',
    'With hot sauce in our bag.',
    'I am thirty-two flavors and then some',
    'At first we were afraid, we were petrified. We will survive.',
    'If we could turn back time, we would have done this already.',
    'What am I supposed to do, sit around and wait for you?',
    'Girls just want to have fun. And make a difference.',
    'Let’s live for the applause.',
    'How long ’til my soul gets it right?',
    'Stronger than yesterday.',
    'Get into the groove.',
    'Strike a pose. Vogue.',
    'You don’t know how far I’d go to ease this precious ache',
    'Clock strikes upon the hour',
    'Let’s stop waiting to exhale',
    'The time has come for you to rally, for your life.',
    'Picture it. Orlando. 2016. Now do something.',
    'No wire hangers. No more shootings.',
    'Don’t fuck with us fellas.',
    'No no. That wasn’t a question.',
    'That’s all.',
    'Too gay. Can function.',
    'Fetch is going to fucking happen.',
    'We are fixing this for all the legendary children.',
    'C-O-N-G-R-E-S-S. Congress. You own everything. Everything is yours to fix.',
    'Hoo-ray for you.',
    'Shade is… I don’t have to tell you to do something. You know to do something.',
    'Cause with y’all vicious motherfuckers it do take nerve.',
    'Category is: mobilization realness',
    'If you don’t have anything nice to say, come stand by me.',
    'No Day But Today',
    'To faggots, lezzies, dykes, crossdressers too',
    'Viva la vie boheme!',
    'Somewhere over the rainbow...',
    'The hills are alive with the sound of our voices',
    'It’s got to happen, happen sometime. Something’s bout to begin.',
    '’Cause you can’t stop the beat',
    'History has its eyes on you',
    'Talk less. Do more.',
    'Just you wait. Just you wait.',
    'Life doesn’t discriminate between the sinners and the saints',
    'I am the one thing in life I can control',
    'Look at where we are. Look at where we started.',
    'Look around, look around. At how lucky we are to be alive right now.',
    'Every day we fight like we’re running out of time.',
    'It’s time to try defying gravity.',
    'Take a GrindR break.',
    'Gun oil. Not gun violence.',
    'More cum shots. Less gun shots.',
    'YASSSSSSSSSSS Queen!',
    'From top to bottom. From sea to shining sea.',
    'Who’s full of argle-bargle now?',
    'I sho’ can tell you what we should do next, okrrrr?',
    'Honey, what’s this? What’s happening? What’s going on?',
    'NRA: You can’t sit with us',
    'If we manage to get this right, they’ll surrender by early light. The world will never be the same.',
    'Do you hear the people sing?',
    '…and all that jazz',
    'NRA is the new Felicia. Bye.'
]
